freeze_files:
    - package.json
    - package-lock.json
    - index.js
    - index.html
    - webpack.config.js
    - .drone.yml
    - meta.yml
    - src/helpers.js
    - src/template.js
    - test/specs/
    - test/nightwatch.json
report_files:
    - CHROME_57.0.2987.98_Linux_test.xml
report_target: .report.json
